# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
#Modrinth
modrinth_versions=["1.20", "1.20.1"]
#`release`, `beta` or `alpha`
release_channel=beta
modrinth_id=betterend
# ModDev
moddev_version=2.0.73-beta
# Minecraft/NeoForge Properties
minecraft_version=1.21.1
neo_version=21.1.248
# Mod Properties
mod_id=betterend
mod_name=Better End
mod_version=20.0.11
maven_group=org.betterx.betterend
archives_base_name=better-end
# Dependencies
# BCLib temporarily commented out for 1.21.1 porting
#bclib_version=21.1.0
#wunderlib_version=21.1.0
emi_version=1.1.13+1.21.1
patchouli_version=1.21-88-NEOFORGE
jei_version=19.8.5.111
